destination: ./_site
auto:        false
lsi:         false
server_port: 4040
pygments:    false
markdown:    maruku
permalink:   date
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex

